# Generated by Django 6.0.3 on 2026-03-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pendingregistration_remove_attendance_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='verification_token',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
